### ISSUE TITLE
Using Modal throws an error or on MacOS

### ISSUE THREAD

**Issue by yunylz** [yesvelte/yesvelte#567]
When I wanted to use the source in https://www.yesvelte.com/docs/modal, I got this error in Mac OS on `npm run dev`
```
[!] RollupError: Invalid value "iife" for option "output.format" - UMD and IIFE output formats are not supported for code-splitting builds.
https://rollupjs.org/configuration-options/#output-format
    at getRollupError (/Users/batin/Desktop/RecTool/node_modules/rollup/dist/shared/parseAst.js:282:41)
    at Object.error (/Users/batin/Desktop/RecTool/node_modules/rollup/dist/shared/parseAst.js:278:42)
    at validateOptionsForMultiChunkOutput (/Users/batin/Desktop/RecTool/node_modules/rollup/dist/shared/rollup.js:19330:28)
    at Bundle.generate (/Users/batin/Desktop/RecTool/node_modules/rollup/dist/shared/rollup.js:19223:17)
    at /Users/batin/Desktop/RecTool/node_modules/rollup/dist/shared/rollup.js:20859:27
    at catchUnfinishedHookActions (/Users/batin/Desktop/RecTool/node_modules/rollup/dist/shared/rollup.js:20332:16)
    at async Promise.all (index 0)
    at Task.run (/Users/batin/Desktop/RecTool/node_modules/rollup/dist/shared/watch.js:257:17)
    at Watcher.run (/Users/batin/Desktop/RecTool/node_modules/rollup/dist/shared/watch.js:183:13)
```

**Comment by TheHadiAhmadi** [comment]
@chaeyan sorry for responding late, I don't have MacOS and I couldn't reproduce it on my machine. 
do you have vite.config.js or rollup.config.js in your project? I don't think this problem is related to yesvelte (I am not sure). it seems problem is related to rollup/vite.
